# Generated by Django 5.0.6 on 2024-08-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0002_alter_user_role_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='district',
            new_name='house_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pincode',
            new_name='postal_code',
        ),
    ]
