# Generated by Django 5.0.6 on 2024-08-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
