# Generated by Django 5.0.6 on 2024-08-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0006_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
