# Generated by Django 5.0.6 on 2024-08-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0011_cattle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
