# Generated by Django 5.0.6 on 2024-09-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0013_vaccinationcenter_alter_cattle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
