# Generated by Django 5.0.6 on 2024-09-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0014_cattle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategory_description',
        ),
    ]
