# Generated by Django 5.0.6 on 2024-09-23 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0020_alter_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccine_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattle_app.vaccinationcenter')),
            ],
        ),
    ]
