# Generated by Django 5.0.6 on 2024-10-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0022_order_orderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattle',
            name='number_of_cattle',
        ),
    ]
