# Generated by Django 5.0.6 on 2024-10-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0023_remove_cattle_number_of_cattle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='rejectmsg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
