# Generated by Django 5.0.6 on 2024-10-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle_app', '0024_cattle_rejectmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0),
        ),
    ]
